name: Script de Testes
on:
  repository_dispatch:
    types: [IntegraRepositorios]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-projeto
        uses: actions/checkout@v7.0.0
      
      - name: Node.js-Install 
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run tests
        run: npx playwright test